name: cervi_scan
description: "Cervi-Scan AI Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.12.1
  image: ^4.1.7
  pdf: ^3.10.8
  printing: ^5.13.1
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cervi_scan_yolo.tflite
    - assets/logo.png
    - assets/best.tflite
    - assets/labels.txt

